version: 2
jobs:
  build-image:

    machine:
      image: ubuntu-1604:201903-01

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build image, test it, tag, publish it
          command: |
            set -e
            ./build_test_tag_publish.sh

  deploy-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud and deploy with helm
          command: |
            set -e
            echo ${GCP_K8S_CREDENTIALS} > /gcp/gcp-credentials.json
            gcloud auth activate-service-account \
              "${SERVICE_ACCOUNT}" \
              --key-file=/gcp/gcp-credentials.json
            gcloud container clusters get-credentials \
              "${CLUSTER}" \
              --zone "${ZONE}" \
              --project "${PROJECT}"
            helm init --client-only
            helm repo add praqma https://praqma-helm-repo.s3.amazonaws.com/
            helm upgrade \
              --install \
              --namespace=beta \
              --set-string containers[0].tag=${CIRCLE_SHA1:0:7} \
              --values .circleci/custom-start-point-values.yaml \
              beta-custom-start-points \
              praqma/cyber-dojo-service \
              --version 0.2.4

  deploy-to-prod:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - checkout
      - run:
          name: Authenticate with gcloud and deploy with helm
          command: |
            set -e
            echo ${GCP_K8S_CREDENTIALS} > /gcp/gcp-credentials.json
            gcloud auth activate-service-account \
              "${SERVICE_ACCOUNT}" \
              --key-file=/gcp/gcp-credentials.json
            gcloud container clusters get-credentials \
              "${CLUSTER}" \
              --zone "${ZONE}" \
              --project "${PROJECT}"
            helm init --client-only
            helm repo add praqma https://praqma-helm-repo.s3.amazonaws.com/
            helm upgrade \
              --install \
              --namespace=prod \
              --set-string containers[0].tag=${CIRCLE_SHA1:0:7} \
              --values .circleci/custom-start-point-values.yaml \
              prod-custom-start-points \
              praqma/cyber-dojo-service \
              --version 0.2.4

workflows:
  version: 2
  build:
    jobs:
      - build-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
      - deploy-to-beta:
          context: cyberdojo-context
          requires:
            - build-image
      - approve-to-prod:
          type: approval
          requires:
            - deploy-to-beta
      - deploy-to-prod:
          context: cyberdojo-context
          requires:
            - approve-to-prod
