
fullnameOverride: "custom-start-points"

replicaCount: 3

service:
  port: 4536
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4536"

volumes:
  - name: custom-start-points-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

containers:
  - name: custom-start-points
    image: cyberdojo/custom-start-points
    securityContext:
      runAsUser: 65534 # nobody
      fsGroup: 65534 # nobody
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: custom-start-points-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    livenessProbe:
      path: /alive?
      port: 4536
    readinessProbe:
      path: /ready?
      port: 4536

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
