
fullnameOverride: "custom-start-points"

daemonSet: true

service:
  annotations:
    prometheus.io/scrape: "true"

volumes:
  - name: custom-start-points-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: File

containers:
  - name: custom-start-points
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: custom-start-points-tmp-dir
        mountPath: /tmp
        readOnly: false
      - mountPath: /var/run/docker.sock
        name: docker-socket
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
      limits:
        memory: 64Mi
    livenessProbe:
      path: /alive?
    readinessProbe:
      path: /ready?

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
