name: Test

on:
  push:
    branches:
      - main

env:
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}
  KOSLI_HOST: ${{ vars.KOSLI_HOST }} # https://app.kosli.com
  KOSLI_ORG: cyber-dojo-trails
  KOSLI_FLOW: ${{ vars.KOSLI_FLOW }} # dashboard
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN_TRAILS }}


jobs:

  variables:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.vars.outputs.image_name }}
      image_tag: ${{ steps.vars.outputs.image_tag }}
      kosli_trail: ${{ steps.vars.outputs.kosli_trail }}
    steps:
    - name: Prepare
      id: vars
      run: |
        TAG=$(echo $GITHUB_SHA | head -c7)
        echo "image_name=cyberdojo/${{ env.KOSLI_FLOW }}:${TAG}" >> ${GITHUB_OUTPUT}
        echo "image_tag=${TAG}" >> ${GITHUB_OUTPUT}
        echo "kosli_trail=${GITHUB_SHA}" >> ${GITHUB_OUTPUT}


  create-kosli-trail:
    needs: [ variables ]
    runs-on: ubuntu-latest
    env:
      KOSLI_TRAIL: ${{ needs.variables.outputs.kosli_trail }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Begin Kosli Trail
        run:
          echo "KOSLI_TRAIL=:{KOSLI_TRAIL}:"
